name: Build, Push, and Deploy Angular Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Production
        run: npm run build:production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t yassingamalz/binaa-center-fe:latest .
          docker push yassingamalz/binaa-center-fe:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: SSH into Oracle Instance and deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.ORACLE_IP }}
          username: ${{ secrets.ORACLE_USERNAME }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            docker pull yassingamalz/binaa-center-fe:latest
            docker stop binaa-center-fe || true
            docker rm binaa-center-fe || true
            docker run -d \
              -p 3200:3200 \
              --name binaa-center-fe \
              --network binaa-network \
              yassingamalz/binaa-center-fe:latest