name: Build, Push, and Deploy Angular Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        run: |
          docker build -t yassingmalaz/binaa-center-fe:latest .
          docker push yassingamalz/binaa-center-fe:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push  # Only runs after the build_and_push job is complete

    steps:
      - name: SSH into Oracle Instance and pull the Docker image
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.ORACLE_IP }}
          username: ${{ secrets.ORACLE_USERNAME }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            docker pull username/binaa-center-fe:latest
            docker stop binaa-center-fe || true
            docker rm binaa-center-fe || true
            docker run -d -p 80:80 --name binaa-center-fe username/binaa-center-fe:latest
